version: "3.8"
services:
  app:
    build: .
    container_name: emotion_analysis_app
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al 8000 del host
    volumes:
      - .:/app  # Mapea la carpeta local a la del contenedor
    restart: always  # Reinicia el contenedor en caso de error
